name: custom_web_socket_client
description: A custom WebSocket client for Dart which includes retry and reconnection logic.

version: 0.1.0

publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  web_socket_channel: ^2.4.0

dev_dependencies:
  mocktail: ^1.0.2
  test: ^1.25.0
  flutter_lints: ^3.0.1